name: CI

on: 
  push:
    branches:
      f/AddCI

jobs:
  test_react:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Git Environment
      uses: actions/checkout@v1
    - name: Setup Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: cd webapp && npm install
    - name: Test web app
      run: npm test
